theme: minima
minima:
  skin: auto
title: Homepage
author: foolishtroy
description: A test portfolio Github Page
permalink: /:categories/:title:output_ext
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM